---
services:
  challenge:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.malware.rule=HostSNI(`malware.serviel.fr`)"
      - "traefik.tcp.routers.malware.entrypoints=CTFtcp"
      - "traefik.tcp.services.malware.loadbalancer.server.port=4000"
      - "traefik.tcp.routers.malware.service=malware"
      - "traefik.tcp.routers.malware.tls.certresolver=myresolver" 
    networks:
      - traefik

networks:
  traefik:
    external: true