---
services:
  challenge:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.pong.rule=HostSNI(`pong.serviel.fr`)"
      - "traefik.tcp.routers.pong.entrypoints=CTFtcp"
      - "traefik.tcp.services.pong.loadbalancer.server.port=4000"
      - "traefik.tcp.routers.pong.service=pong"
      - "traefik.tcp.routers.pong.tls.certresolver=myresolver" 
    networks:
      - traefik

networks:
  traefik:
    external: true