---
services:
  challenge:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.lottery.rule=HostSNI(`lottery.serviel.fr`)"
      - "traefik.tcp.routers.lottery.entrypoints=CTFtcp"
      - "traefik.tcp.services.lottery.loadbalancer.server.port=4000"
      - "traefik.tcp.routers.lottery.service=lottery"
      - "traefik.tcp.routers.lottery.tls.certresolver=myresolver" 
    networks:
      - traefik

networks:
  traefik:
    external: true