---
services:
  challenge:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.zoo.rule=HostSNI(`zoo.serviel.fr`)"
      - "traefik.tcp.routers.zoo.entrypoints=CTFtcp"
      - "traefik.tcp.services.zoo.loadbalancer.server.port=4000"
      - "traefik.tcp.routers.zoo.service=zoo"
      - "traefik.tcp.routers.zoo.tls.certresolver=myresolver" 
    networks:
      - traefik

networks:
  traefik:
    external: true